# Generated by Django 2.0.5 on 2018-12-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pull', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pullimage',
            name='url',
        ),
        migrations.RemoveField(
            model_name='pullimage',
            name='user',
        ),
    ]
