# Generated by Django 2.0.5 on 2018-12-10 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pull', '0002_colors_pullimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pull.Categories')),
            ],
            options={
                'db_table': 'pull_model',
            },
        ),
    ]
